### ISSUE TITLE
Not working on a edited response sheet.

### ISSUE THREAD

**Issue by nithinkodadhavadee** [GATEOverflow/GATE-Marks-Evaluator#12]
I copied the whole code of the response sheet, edited a few of the answers just so to check what would have been my rank if I had answered a few questions correctly.
Then when I tried to paste the path to the file in the input box, I got an error saying expected 65 questions, got none.
So I hosted the file on my GitHub account and pasted that link in the URL input box. It did open up the file, all the edits I made are shown correctly on the gate overflow rank predictor page, but it doesn't calculate the score. I just get an empty score table.
![image](https://user-images.githubusercontent.com/50230678/110925346-14d09f80-8349-11eb-9a6e-2a4563e4d40a.png)

I don't know why that is happening, I don't know if that is intentional. Just a reply would be great.
Thank you

**Comment by arjunsuresh** [comment]
yes, that may not work as the app considers only the official answer response URLs. If you want to know your estimated rank why dont you simply calculate the mark and enter that in the VisualizeMarks.php page?

**Comment by nithinkodadhavadee** [comment]
I didn't find a text box to enter the marks. Where or how should I do that?

**Comment by arjunsuresh** [comment]
In mymarks box at https://gateoverflow.in/mymarks/VisualizeMarks.php
